[package]
name = "kindle-dash-next-wakeup"
version = "0.1.0"
authors = ["Pascal Widdershoven <hello@pascalw.me>"]
edition = "2018"

[dependencies]
cron-parser = "0.7.7"
chrono = "0.4.19"
chrono-tz = "0.5.3"
pico-args = "0.4.0"

[[bin]]
name = "next-wakeup"
path = "src/main.rs"
