[server]
server_dir = "./data/"  # Use relative path that works in both environments

[image]
width = 1072
height = 1448

[calendar]
display_timezone = "Europe/London"
days_to_show = 2
ids = {"holmbergs" = "10a2dd68e51bb17689c7ccf4f4722d1f445c59c86430577b425c33ccee27be2e@group.calendar.google.com"}
creds = "./credentials_service.json"  # Use relative path that works in both environments

[tasks]
project_id = "6MmR9G3CcW4VF27h"

# [weather]
# latitude = 51.5074
# longitude = -0.1278